config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :accounts
resources :buyers
resources :carts
resources :line_items
resources :orders
resources :products
resources :sellers
resources :super_accounts

    root to: "accounts#index"
  end

  devise_for :accounts,  :controllers => { :registrations => 'registrations' }
  resources :orders
  get 'hello_world', to: 'hello_world#index'
  get 'search', to: 'store#search'
  mount ActionCable.server => '/cable'
  resources :line_items do
    put 'decrease', on: :member
    post 'decrease', on: :member
  end
  resources :carts
  root 'store#index', as: 'store_index'

  resources :products
  
  resources :sellers do
    resources :products

    member do
        get 'orders', to: 'line_items#show_orders_for_seller'
    end
end

resources :buyers do
    resources :orders
end
  
  resources :buyers, only: [:edit, :update]
  resources :sellers, only: [:edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
  <div class="container">
    <div class="navbar-header navbar-right">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div class="collapse navbar-collapse navbar-right">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Catalog <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
                <li><%= link_to 'Regular', store_index_path(spa: false) %></li>
                <li><%= link_to "SPA", store_index_path(spa: true) %></li>
        </ul>
</li>

<% if account_signed_in? %>

   <% if current_account.accountable_type == "SuperAccount" %>
        <li><%= link_to 'Admin Dashboard', admin_root_path %></li>                  
  <% else %>

    <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Resources <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                    <% if current_account.accountable_type == "Seller" %>
                        <li><%= link_to 'My Products', seller_products_path(current_account.accountable_id) %></li>
                        <li><%= link_to 'My Orders', orders_seller_path(current_account.accountable_id) %></li>
                    <% else %>
                        <li><%= link_to 'My Orders', buyer_orders_path(current_account.accountable_id) %></li>
                    <% end %>
            </ul>
    </li>
  <% end %>  
  
  <% if current_account.accountable_type != "SuperAccount" %>
    <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Settings (<%= (current_account.accountable.name.nil? or current_account.accountable.name == "") ? "No Name" : current_account.accountable.name %>) <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
              <% if current_account.accountable_type == "Seller" %>
                <li><%= link_to 'Seller Profile', edit_seller_path(current_account.accountable_id) %></li>
              <% else %>
                <li><%= link_to 'Buyer Profile', edit_buyer_path(current_account.accountable_id) %></li>
              <% end %>
              <li><%= link_to 'Account Settings', edit_account_registration_path %></li>
        </ul>
    </li>
  <% end %>
    <li><%= link_to 'Sign out', destroy_account_session_path, :method=>'delete' %></li>

<% else %>

    <li><%= link_to 'Sign in', new_account_session_path %></li>
    <li><%= link_to 'Sign up', new_account_registration_path %></li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">

  <header>
      <%= render 'layouts/navigation' %>
  </header>

  <div id="columns">
    <% if @spa.nil? %>
      <% if @cart  %>
      <div id="side">
        <div id="cart">

            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %> 
            <% end %>

        </div>
      </div>
      <% end %> 
    <% end %>

    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>